/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moja_firma.view;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import moja_firma.controller.ObradaOsoblja;
import moja_firma.model.Osoba;
import moja_firma.utility.Pomocno;
import moja_firma.utility.Uloga;

/**
 *
 * @author Dubravka
 */
public class Osoblje extends Upozorenja {
    
    int width = (Toolkit.getDefaultToolkit().getScreenSize().width/2)-475;
    int height = (Toolkit.getDefaultToolkit().getScreenSize().height/2)-220;
    private ObradaOsoblja obradaAdministratora;
    private Osoba odabrano;
    private SimpleDateFormat df;

    /**
     * Creates new form Operateri
     */
    public Osoblje() {
        initComponents();
        obradaAdministratora = new ObradaOsoblja();
         setLocation(width, height);
        jLabel13.setIcon(new javax.swing.ImageIcon("slike" + File.separator + "Pozadine" + File.separator + "NestoPlavoV.png" ));
        lista.setModel(new DefaultListModel<Osoba>());
        setTitle("ADMINISTRATOR MOJE FIRME: "+Pomocno.getOsoba().getImePrezime()); 
        
        DefaultComboBoxModel<Uloga> m = new DefaultComboBoxModel<>();
        for (Uloga u : Pomocno.ulogeUSustavu()) {
            m.addElement(u);
        }
        uloga.setModel(m);
        
       df = new SimpleDateFormat(Pomocno.getOsoba().getFormatDatuma());
        labelaDatum.setText(labelaDatum.getText() + "("+ Pomocno.getOsoba().getFormatDatuma() 
                + ", npr: " + df.format(new Date()) +")");
        
    }
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        uvjet = new javax.swing.JTextField();
        akcijaTrazi = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        lista = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        korisnicko_ime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lozinka = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        ime = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        prezime = new javax.swing.JTextField();
        akcijaDodajNovi = new javax.swing.JButton();
        akcijaObrisi = new javax.swing.JButton();
        akcijaPromijeni = new javax.swing.JButton();
        akcijaOdustani = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelaDatum = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        aktivan = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        primjedba = new javax.swing.JTextArea();
        iban = new javax.swing.JTextField();
        telefon = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        mobitel = new javax.swing.JTextField();
        naziv = new javax.swing.JTextField();
        datumrodenja = new javax.swing.JTextField();
        adresa = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        uloga = new javax.swing.JComboBox();
        oib = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("OSOBLJE");
        setBackground(new java.awt.Color(204, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(950, 650));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Uvjet(* za sve)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        uvjet.setBackground(new java.awt.Color(204, 255, 255));
        uvjet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                uvjetKeyPressed(evt);
            }
        });
        getContentPane().add(uvjet, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 120, -1));

        akcijaTrazi.setBackground(new java.awt.Color(0, 204, 204));
        akcijaTrazi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        akcijaTrazi.setText("TRAŽI");
        akcijaTrazi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        akcijaTrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaTraziActionPerformed(evt);
            }
        });
        getContentPane().add(akcijaTrazi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 70, -1));

        lista.setBackground(new java.awt.Color(204, 255, 255));
        lista.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listaKeyPressed(evt);
            }
        });
        lista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaValueChanged(evt);
            }
        });
        jScrollPane.setViewportView(lista);

        getContentPane().add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 246, 280));

        jLabel2.setText("Korisničko ime");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 104, -1));

        korisnicko_ime.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(korisnicko_ime, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 210, -1));

        jLabel3.setText("Lozinka");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 82, -1));

        lozinka.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(lozinka, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 210, -1));

        jLabel5.setText("Ime");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 72, -1));

        ime.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(ime, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 210, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(816, 0, 62, -1));

        prezime.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(prezime, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 210, -1));

        akcijaDodajNovi.setBackground(new java.awt.Color(0, 204, 204));
        akcijaDodajNovi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        akcijaDodajNovi.setText("DODAJ NOVI");
        akcijaDodajNovi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        akcijaDodajNovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaDodajNoviActionPerformed(evt);
            }
        });
        getContentPane().add(akcijaDodajNovi, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 240, 49));

        akcijaObrisi.setBackground(new java.awt.Color(0, 204, 204));
        akcijaObrisi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        akcijaObrisi.setText("OBRIŠI");
        akcijaObrisi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        akcijaObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaObrisiActionPerformed(evt);
            }
        });
        getContentPane().add(akcijaObrisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 240, 49));

        akcijaPromijeni.setBackground(new java.awt.Color(0, 204, 204));
        akcijaPromijeni.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        akcijaPromijeni.setText("PROMIJENI");
        akcijaPromijeni.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        akcijaPromijeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaPromijeniActionPerformed(evt);
            }
        });
        getContentPane().add(akcijaPromijeni, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 49));

        akcijaOdustani.setBackground(new java.awt.Color(0, 204, 204));
        akcijaOdustani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        akcijaOdustani.setText("ODUSTANI");
        akcijaOdustani.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        akcijaOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaOdustaniActionPerformed(evt);
            }
        });
        getContentPane().add(akcijaOdustani, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 230, 49));

        jLabel4.setText("Naziv pravnog subjekta");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        jLabel7.setText("OIB");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 104, -1));

        jLabel8.setText("Telefon");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 115, -1));

        jLabel9.setText("Mobitel");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, -1));

        jLabel10.setText("Adresa");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        jLabel11.setText("email");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, -1, -1));

        jLabel12.setText("IBAN");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, -1, -1));

        labelaDatum.setText("Datum rođenja");
        getContentPane().add(labelaDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, -1, -1));

        jLabel15.setText("Primjedba");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));

        aktivan.setBackground(new java.awt.Color(0, 204, 204));
        aktivan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aktivan.setText("Aktivan");
        getContentPane().add(aktivan, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 570, 210, 45));

        primjedba.setBackground(new java.awt.Color(204, 255, 255));
        primjedba.setColumns(20);
        primjedba.setRows(5);
        jScrollPane1.setViewportView(primjedba);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 246, 130));

        iban.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(iban, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 212, -1));

        telefon.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(telefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 210, -1));

        email.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 212, -1));

        mobitel.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(mobitel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 210, -1));

        naziv.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(naziv, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 210, -1));

        datumrodenja.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(datumrodenja, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 520, 212, -1));

        adresa.setBackground(new java.awt.Color(204, 255, 255));
        adresa.setSelectedTextColor(new java.awt.Color(0, 204, 204));
        getContentPane().add(adresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, 210, -1));

        jLabel14.setText("Prezime");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        uloga.setBackground(new java.awt.Color(204, 255, 255));
        uloga.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "administrator", "autor", "uposlenik", "vanjski_suradnik", "narucitelj" }));
        getContentPane().add(uloga, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 160, -1));

        oib.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(oib, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 210, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pozadine/NestoPlavoV.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void akcijaTraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaTraziActionPerformed
          
        cistiPolja();
      
       
         List<Osoba> osobe = obradaAdministratora.
                dohvati(((Uloga)uloga.getSelectedItem()).getBaza());
        
        DefaultListModel<Osoba> m = new DefaultListModel<>();
        for (Osoba osoba : osobe) {
            m.addElement(osoba);
        }
        lista.setModel(m);
        
    }//GEN-LAST:event_akcijaTraziActionPerformed

    private void listaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaValueChanged
          reset();
        odabrano = (Osoba) lista.getSelectedValue();
        if(odabrano==null){
            return;
        }
        korisnicko_ime.setText(odabrano.getKorisnicko_ime());
        lozinka.setText(odabrano.getLozinka());
        ime.setText(odabrano.getIme());
        prezime.setText(odabrano.getPrezime());
        naziv.setText(odabrano.getNaziv());
        oib.setText(odabrano.getOib());
        telefon.setText(odabrano.getTelefon());
        mobitel.setText(odabrano.getMob());
        email.setText(odabrano.getEmail());
        adresa.setText(odabrano.getAdresa());
        iban.setText(odabrano.getIban());
        aktivan.setSelected(odabrano.isAktivan());
        primjedba.setText(odabrano.getPrimjedba());
        
        
        SimpleDateFormat df = new SimpleDateFormat(Pomocno.FORMAT_DATUM_UNOS);   
        try {
            datumrodenja.setText(df.format(odabrano.getDatumrodenja()));
        } catch (Exception e) {
            datumrodenja.setText("");
        }
    }//GEN-LAST:event_listaValueChanged

    private void akcijaDodajNoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaDodajNoviActionPerformed
              reset();
        if(korisnicko_ime.getText().trim().isEmpty()){
           greska(korisnicko_ime, "Obavezno korisničko ime");
           return;
       }
        
        if(!obradaAdministratora.provjeraKorisnika(korisnicko_ime.getText().trim())){
             greska(korisnicko_ime, "Korisnik postoji u bazi, odabarite drugi");
           return;
        }
        
        
        if((new String(lozinka.getPassword())).trim().isEmpty()){
           greska(lozinka, "Obavezno lozinka");
           return;
       }
     
       if(ime.getText().trim().isEmpty()){
           greska(ime, "Obavezno ime");
           return;
       }
        if(prezime.getText().trim().isEmpty()){
           greska(prezime, "Obavezno prezime");
           return;
       }
        if(uvjet.getText().trim().isEmpty()){
            greska(uvjet,"Upišite ulogu");
            return;
        }
        
       
        Osoba o = new Osoba();
         o=popuni(o);
        
        o=obradaAdministratora.dodaj(o);
        
        
         
         if(datumrodenja.getText().trim().length()>0){
        try {
            o.setDatumrodenja(df.parse(datumrodenja.getText().trim().replace(" ","")));
        } catch (Exception e) {
            greska(datumrodenja, "datum nije dobrog formata");
            return;
        }
        }else{
            o.setDatumrodenja(null);
        }
        
      
        
                  DefaultListModel<Osoba> m =(DefaultListModel<Osoba>) lista.getModel();

            m.addElement(o);
         lista.repaint();
       cistiPolja();
       reset();
        
    }//GEN-LAST:event_akcijaDodajNoviActionPerformed
   private Osoba popuni(Osoba o){
        o.setIme(ime.getText().trim());
        o.setPrezime(prezime.getText().trim());
        o.setUloga(uvjet.getText().trim());
        o.setKorisnicko_ime(korisnicko_ime.getText().trim());
        o.setLozinka(new String(lozinka.getPassword()));
        o.setNaziv(naziv.getText().trim());
        o.setOib(oib.getText());
        o.setTelefon(telefon.getText().trim());
        o.setMob(mobitel.getText().trim());
        o.setEmail(email.getText().trim());
        o.setAdresa(adresa.getText().trim());
        o.setIban(iban.getText().trim());
        o.setPrimjedba(primjedba.getText().trim());
        o.setAktivan(aktivan.isSelected());
        
        if(datumrodenja.getText().trim().length()>0){
        try {
            o.setDatumrodenja(df.parse(datumrodenja.getText().trim().replace(" ","")));
        } catch (Exception e) {           
        }
        }else{
            o.setDatumrodenja(null);
        } 
        return o;
    }
    
    private void cistiPolja(){
        korisnicko_ime.setText("");
        lozinka.setText("");
        ime.setText("");
        prezime.setText("");
        naziv.setText("");
        oib.setText("");
        telefon.setText("");
        mobitel.setText("");
        email.setText("");
        adresa.setText("");
        iban.setText("");
        datumrodenja.setText("");
        primjedba.setText("");
        aktivan.setSelected(false);
        
    }
    
    private void akcijaObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaObrisiActionPerformed
        odabrano = (Osoba) lista.getSelectedValue();
        if(odabrano==null){
            return;
        }
        if(JOptionPane.showConfirmDialog(getParent(), "Jeste li sigurni da želite obrisati " + odabrano.getImePrezime() + "?","Brisanje administratora",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==JOptionPane.NO_OPTION){
           return;
       }
       
       if(!obradaAdministratora.obrisi(odabrano)){
           return;
       }
       
       DefaultListModel<Osoba> m = (DefaultListModel<Osoba>) lista.getModel();
       m.removeElement(odabrano);
       lista.repaint();
       cistiPolja();
    }//GEN-LAST:event_akcijaObrisiActionPerformed

    private void akcijaPromijeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaPromijeniActionPerformed
        if(odabrano==null){
    return;
}       
        reset();
//kontorle
        if(!odabrano.getKorisnicko_ime().equals(korisnicko_ime.getText().trim())){
            if(!obradaAdministratora.provjeraKorisnika(korisnicko_ime.getText().trim())){
                 greska(korisnicko_ime, "Korisničko ime postoji, odaberite drugo korisničko ime");
                return;
            }
            
        }
        if(new String(lozinka.getPassword()).trim().isEmpty() ){
             greska(lozinka, "Lozinka obavezno");
     
        }
        
          if(ime.getText().trim().isEmpty()){
           greska(ime, "Obavezno ime");
           return;
       }
        if(prezime.getText().trim().isEmpty()){
           greska(prezime, "Obavezno prezime");
           return;
       }
        if(uvjet.getText().trim().isEmpty()){
            greska(uvjet, "Obavezno navedite ulogu");
            return;
        }
          if(datumrodenja.getText().trim().length()>0){
        try {
            odabrano.setDatumrodenja(df.parse(datumrodenja.getText().trim().replace(" ","")));
        } catch (Exception e) {
            greska(datumrodenja, "datum nije dobrog formata");
            return;
        }
        }else{
            odabrano.setDatumrodenja(null);
        }
        odabrano=popuni(odabrano);
       odabrano.setKorisnicko_ime(korisnicko_ime.getText().trim());
        odabrano.setLozinka(new String(lozinka.getPassword()).trim());
        odabrano.setIme(ime.getText().trim());
        odabrano.setPrezime(prezime.getText().trim());
        odabrano.setUloga(uvjet.getText().trim());
        
        //promjena u bazi
        if(!obradaAdministratora.promijeni(odabrano)){
            return;
        }
        
        //dodavanje/postavljanje
        //nekada ne radi dobro
        lista.repaint();
         cistiPolja();
         reset();
    }//GEN-LAST:event_akcijaPromijeniActionPerformed

    private void uvjetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uvjetKeyPressed
         if(evt.getKeyCode()==
                KeyEvent.VK_ENTER){
            akcijaTraziActionPerformed(null);
        }
    }//GEN-LAST:event_uvjetKeyPressed

    private void listaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listaKeyPressed
        if(evt.getKeyCode()==
                KeyEvent.VK_ENTER){
            listaValueChanged(null);
        }
    }//GEN-LAST:event_listaKeyPressed

    private void akcijaOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaOdustaniActionPerformed
dispose();

    }//GEN-LAST:event_akcijaOdustaniActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresa;
    private javax.swing.JButton akcijaDodajNovi;
    private javax.swing.JButton akcijaObrisi;
    private javax.swing.JButton akcijaOdustani;
    private javax.swing.JButton akcijaPromijeni;
    private javax.swing.JButton akcijaTrazi;
    private javax.swing.JCheckBox aktivan;
    private javax.swing.JTextField datumrodenja;
    private javax.swing.JTextField email;
    private javax.swing.JTextField iban;
    private javax.swing.JTextField ime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField korisnicko_ime;
    private javax.swing.JLabel labelaDatum;
    private javax.swing.JList lista;
    private javax.swing.JPasswordField lozinka;
    private javax.swing.JTextField mobitel;
    private javax.swing.JTextField naziv;
    private javax.swing.JTextField oib;
    private javax.swing.JTextField prezime;
    private javax.swing.JTextArea primjedba;
    private javax.swing.JTextField telefon;
    private javax.swing.JComboBox uloga;
    private javax.swing.JTextField uvjet;
    // End of variables declaration//GEN-END:variables

  
}
