/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moja_firma.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.Timer;

/**
 *
 * @author Dubravka
 */
public class Pozdrav extends javax.swing.JFrame {

    
    private Timer t = null;
    private int brojac = 0;
    /**
     * Creates new form Pozdrav
     */
    public Pozdrav() {
        initComponents();
        setLocationRelativeTo(null);
        jLabel3.setIcon(new javax.swing.ImageIcon("slike" + File.separator + "Pozadine" + File.separator + "NestoPlavo.png" ));
      
        t = new Timer(50, new ActionListener() {

              @Override
            public void actionPerformed(ActionEvent e) {
                
                brojac ++;
                jProgressBar1.setValue(brojac);
                if (jProgressBar1.getValue() < 100) {
                    jProgressBar1.setValue(jProgressBar1.getValue() + 1);                                        
                }else {
                    t.stop();
                    dispose();
                    new Autorizacija().setVisible(true);
                }               
               
            }          
        });
        t.start();     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        akcijalogo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MOJA FIRMA");
        setMaximumSize(new java.awt.Dimension(560, 460));
        setMinimumSize(new java.awt.Dimension(560, 460));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jProgressBar1.setBackground(new java.awt.Color(204, 255, 255));
        jProgressBar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jProgressBar1.setForeground(new java.awt.Color(0, 204, 204));
        jProgressBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(110, 350, 340, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html>DOBRO DOŠLI U <br />          MOJU FIRMU</html>");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 70, 295, 86);

        akcijalogo.setBackground(new java.awt.Color(204, 255, 255));
        akcijalogo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        akcijalogo.setForeground(new java.awt.Color(0, 102, 102));
        akcijalogo.setText("LOGO");
        akcijalogo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(akcijalogo);
        akcijalogo.setBounds(210, 190, 134, 96);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pozadine/NestoPlavo.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 560, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton akcijalogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
