/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moja_firma.view;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import moja_firma.controller.ObradaOsoblja;
import moja_firma.controller.ObradaRada;
import moja_firma.model.Materijal;
import moja_firma.model.Rad;
import moja_firma.utility.Pomocno;

/**
 *
 * @author Dubravka
 */
public class Radovi extends Upozorenja {
    
     int width = (Toolkit.getDefaultToolkit().getScreenSize().width/2)-475;
     int height = (Toolkit.getDefaultToolkit().getScreenSize().height/2)-220;
     private ObradaRada obrada;
     private Rad odabrano;
     private ObradaOsoblja obradaAdministratora;

    /**
     * Creates new form Radovi
     */
    public Radovi() {
        initComponents();
           setLocation(width, height);
            obradaAdministratora = new ObradaOsoblja();
          jLabel10.setIcon(new javax.swing.ImageIcon("slike" + File.separator + "Pozadine" + File.separator + "NestoPlavoV.png" ));
        obrada=new ObradaRada();
        lista.setModel(new DefaultListModel<Rad>());
       setTitle("Materijali moje firme: " + 
               Pomocno.getOsoba().getImePrezime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        uvjet = new javax.swing.JTextField();
        akcijaTrazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList();
        akcijaPromijeni = new javax.swing.JButton();
        akcijaDodajNovi = new javax.swing.JButton();
        akcijaobrisi = new javax.swing.JButton();
        akcijaOdustani = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        prezime = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        uloga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nazivrada = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cijenarada = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        kolicina = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        korisnicko_ime = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("RADOVI");
        setMinimumSize(new java.awt.Dimension(950, 650));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Uvjet(* za sve)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 190, -1));

        uvjet.setBackground(new java.awt.Color(204, 255, 255));
        uvjet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                uvjetKeyPressed(evt);
            }
        });
        getContentPane().add(uvjet, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 150, 30));

        akcijaTrazi.setBackground(new java.awt.Color(0, 204, 204));
        akcijaTrazi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        akcijaTrazi.setText("TRAŽI");
        akcijaTrazi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        akcijaTrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaTraziActionPerformed(evt);
            }
        });
        getContentPane().add(akcijaTrazi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 80, 30));

        lista.setBackground(new java.awt.Color(204, 255, 255));
        lista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listaKeyPressed(evt);
            }
        });
        lista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lista);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 240, 340));

        akcijaPromijeni.setBackground(new java.awt.Color(0, 204, 204));
        akcijaPromijeni.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        akcijaPromijeni.setText("PROMIJENI");
        akcijaPromijeni.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        akcijaPromijeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaPromijeniActionPerformed(evt);
            }
        });
        getContentPane().add(akcijaPromijeni, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 49));

        akcijaDodajNovi.setBackground(new java.awt.Color(0, 204, 204));
        akcijaDodajNovi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        akcijaDodajNovi.setText("DODAJ NOVI");
        akcijaDodajNovi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        akcijaDodajNovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaDodajNoviActionPerformed(evt);
            }
        });
        getContentPane().add(akcijaDodajNovi, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 240, 49));

        akcijaobrisi.setBackground(new java.awt.Color(0, 204, 204));
        akcijaobrisi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        akcijaobrisi.setText("OBRIŠI");
        akcijaobrisi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        akcijaobrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaobrisiActionPerformed(evt);
            }
        });
        getContentPane().add(akcijaobrisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 240, 49));

        akcijaOdustani.setBackground(new java.awt.Color(0, 204, 204));
        akcijaOdustani.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        akcijaOdustani.setText("ODUSTANI");
        akcijaOdustani.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        akcijaOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akcijaOdustaniActionPerformed(evt);
            }
        });
        getContentPane().add(akcijaOdustani, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 230, 49));

        jLabel2.setText("Ime");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 214, 90, 20));

        ime.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(ime, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 320, 30));

        jLabel3.setText("Prezime");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 294, 90, 20));

        prezime.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(prezime, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 320, 30));

        jLabel4.setText("Uloga");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 384, 50, 20));

        uloga.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(uloga, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 320, 30));

        jLabel5.setText("Naziv rada");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 134, 80, 20));

        nazivrada.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(nazivrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 320, 30));

        jLabel6.setText(" Cijena rada u kn");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 474, 110, 20));

        cijenarada.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(cijenarada, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 320, 30));

        jLabel7.setText("Količina");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 564, 60, 20));

        kolicina.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(kolicina, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 560, 320, 30));

        jLabel8.setText("Korisničko ime");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 160, -1));

        korisnicko_ime.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(korisnicko_ime, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 240, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pozadine/NestoPlavoV.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void akcijaTraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaTraziActionPerformed
          cistiPolja();

        List<Rad> entiteti = obrada.
        dohvati(uvjet.getText());

        DefaultListModel<Rad> m = new DefaultListModel<>();
        for (Rad e : entiteti) {
            m.addElement(e);
        }
        lista.setModel(m);
    }//GEN-LAST:event_akcijaTraziActionPerformed

    
    private void akcijaPromijeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaPromijeniActionPerformed
          if(odabrano==null){
            return;
        }
        reset();
        //kontorle
        if(ime.getText().trim().isEmpty()){
            greska(ime, "Obavezno ime");
            return;
        }
       
        if(prezime.getText().trim().isEmpty()){
            greska(prezime, "Obavezno prezime");
            return;
        }
        
        if(uloga.getText().trim().isEmpty()){
            greska(uloga, "Obavezno uloga");
            return;
        }
        
        if(nazivrada.getText().trim().isEmpty()){
            greska(nazivrada, "Obavezno nazivrada");
            return;
        }
         if(korisnicko_ime.getText().trim().isEmpty()){
            greska(korisnicko_ime, "Obavezno korianičko ime");
            return;
        }
         
        
         odabrano=popuni(odabrano);
        
       

        //promjena u bazi
        if(!obrada.promjeni(odabrano)){
            return;
        }
           //promjena u bazi
        if(!obradaAdministratora.promijeni(odabrano)){
            return;
        }

        lista.repaint();
        cistiPolja();
         reset();
    }//GEN-LAST:event_akcijaPromijeniActionPerformed
        
        private Rad popuni(Rad o){
        o.setIme(ime.getText());
        o.setPrezime(prezime.getText());
        o.setNazivrada(nazivrada.getText());
        o.setCijenarada(new BigDecimal(cijenarada.getText().trim()));
        o.setKolicina(new BigDecimal(kolicina.getText().trim()));
        o.setUloga(uloga.getText());
        o.setKorisnicko_ime(korisnicko_ime.getText().trim());
        
        return o;
    }
    private void akcijaDodajNoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaDodajNoviActionPerformed
         reset();
        if(ime.getText().trim().isEmpty()){
            greska(ime, "Obavezno ime");
            return;
        }
       
        if(prezime.getText().trim().isEmpty()){
            greska(prezime, "Obavezno prezime");
            return;
        }
         if(korisnicko_ime.getText().trim().isEmpty()){
            greska(korisnicko_ime, "Obavezno korisničko ime");
            return;
        }                
        if(!obradaAdministratora.provjeraKorisnika(korisnicko_ime.getText().trim())){
             greska(korisnicko_ime, "Korisnik postoji u bazi, odabarite drugi");
           return;
        }

        Rad o = new Rad();
        o=popuni(o);
       
        
        o=obrada.dodaj(o);
        if(o==null){
            //obavijest
            return;
        }
        DefaultListModel<Rad> m =(DefaultListModel<Rad>) lista.getModel();
        m.addElement(o);

    }//GEN-LAST:event_akcijaDodajNoviActionPerformed

    private void akcijaobrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaobrisiActionPerformed
              odabrano = (Rad) lista.getSelectedValue();
        if(odabrano==null){
            return;
        }
        if(JOptionPane.showConfirmDialog(getParent(), "Jeste li sigurni da želite obrisati " + odabrano.getNaziv() + "?","Brisanje rada",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==JOptionPane.NO_OPTION){
           return;
       }
       
       if(!obrada.obrisi(odabrano)){
           return;
       }
       
       DefaultListModel<Rad> m = (DefaultListModel<Rad>) lista.getModel();
       m.removeElement(odabrano);
        lista.repaint();
       cistiPolja();
             
    }//GEN-LAST:event_akcijaobrisiActionPerformed

    private void akcijaOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akcijaOdustaniActionPerformed
         dispose();
        
    }//GEN-LAST:event_akcijaOdustaniActionPerformed

    private void listaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaValueChanged
          reset();
        odabrano = (Rad) lista.getSelectedValue();
        if(odabrano==null){
            return;
        }
        
        ime.setText(odabrano.getIme());
        prezime.setText(odabrano.getPrezime());
        nazivrada.setText(odabrano.getNazivrada());
        uloga.setText(odabrano.getUloga());
        cijenarada.setText(String.valueOf(odabrano.getCijenarada()));
        kolicina.setText(String.valueOf(odabrano.getKolicina()));
        korisnicko_ime.setText(odabrano.getKorisnicko_ime());
        
    }//GEN-LAST:event_listaValueChanged

    private void listaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listaKeyPressed
         if(evt.getKeyCode()==
                KeyEvent.VK_ENTER){
            listaValueChanged(null);
        }
    }//GEN-LAST:event_listaKeyPressed

    private void uvjetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uvjetKeyPressed
          if(evt.getKeyCode()==
            KeyEvent.VK_ENTER){
            akcijaTraziActionPerformed(null);
        }
    }//GEN-LAST:event_uvjetKeyPressed

    /**
     * @param args the command line arguments
     */
      private void cistiPolja(){
        
        nazivrada.setText("");
        ime.setText("");
        prezime.setText("");
        kolicina.setText("");
        uloga.setText("");
        cijenarada.setText("");
        korisnicko_ime.setText("");
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton akcijaDodajNovi;
    private javax.swing.JButton akcijaOdustani;
    private javax.swing.JButton akcijaPromijeni;
    private javax.swing.JButton akcijaTrazi;
    private javax.swing.JButton akcijaobrisi;
    private javax.swing.JTextField cijenarada;
    private javax.swing.JTextField ime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kolicina;
    private javax.swing.JTextField korisnicko_ime;
    private javax.swing.JList lista;
    private javax.swing.JTextField nazivrada;
    private javax.swing.JTextField prezime;
    private javax.swing.JTextField uloga;
    private javax.swing.JTextField uvjet;
    // End of variables declaration//GEN-END:variables
}
